prpc:
  server:
    protocol: prpc
    registryCenter:
      naming: zookeeper
      address: 127.0.0.1:2181
    codec: protobuf
    timeout: 30000
    groups:
      - group: default
        registryCenter:
          naming: zookeeper
          address: 127.0.0.1:2181
        codec: protobuf
        protocol: prpc
        timeout: 30000
        basePackage: com.weaponlin.inf.prpc.api
  client:
    protocol: prpc
    registryCenter:
      naming: zookeeper
      address: 127.0.0.1:2181
    codec: protobuf
    loadBalance: roundrobin
    cluster: failfast
    groups:
      - group: default
        registryCenter:
          naming: zookeeper
          address: 127.0.0.1:2181
        codec: protobuf
        loadBalance: roundrobin
        protocol: prpc
        timeout: 30000
        basePackage: com.weaponlin.inf.prpc.api

server:
  port: 8081
